import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './component/Header'
import { ThemeProvider } from './context/themeContext'
import { BookProvider } from './context/bookContext'
import { ModalProvider } from './context/modalContext'
import ModalControl from './component/ModalControl'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Books Store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <BookProvider>
            <ModalProvider>
              <Header />
              {children}
              <ModalControl />
            </ModalProvider>
          </BookProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
